[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Set-Cookie = "cross-site-cookie=true; SameSite=None; Secure"
    X-Content-Type-Options = "nosniff"
